[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
aster-nix = { path = "../kernel" }
ostd = { path = "../ostd" }
osdk-frame-allocator = { path = "../osdk/deps/frame-allocator" }
osdk-heap-allocator = { path = "../osdk/deps/heap-allocator" }


[lints]
workspace = true
